#!/bin/bash

#해당 타겟 실행
./../../PacketGenerator/bin/PacketGenerator ./../../PacketGenerator/PDL.xml

#cp [파일] [타겟 주소] - 파일을 해당 타겟 주소로 복사 -f : 덮어쓰기
cp -f ./GenPackets.cs ./../../DummyClient/Packet
cp -f ./GenPackets.cs ./../../Server/Packet